{application,jane_web,
             [{description,"jane_web"},
              {vsn,"1"},
              {modules,[index_dtl,jane_web,jane_control_app,
                        jane_web_resource,jane_control_sup,mywebdemo]},
              {registered,[]},
              {applications,[kernel,stdlib,inets,crypto,mochiweb,webmachine]},
              {mod,{jane_web_app,[]}},
              {env,[]}]}.
